In [2]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
#around function - rounding
import numpy as np  
arr = np.array([20.8999,67.89899,54.63409])  
print(np.around(arr,1))
print(np.around(arr,0))

[20.9 67.9 54.6]
[21. 68. 55.]


In [5]:
#floor function - integer value of number
import numpy as np  
arr = np.array([20.8,67.99,54.09])  
print(np.floor(arr))

[20. 67. 54.]


In [4]:
#ceil function - integer value +1
import numpy as np  
arr = np.array([20.8,67.99,54.09])  
print(np.ceil(arr))

[21. 68. 55.]


In [3]:
#Arithmetic operations
import numpy as np
 
a = np.array([1, 2, 3, 4])
 
# add 5 to every element
print ( a+5)
 
# subtract 2 from each element
print ( a-2)
 
# multiply each element by 5 
print (a*10)
 
# divide each element by 2
print ( a/2)

[6 7 8 9]
[-1  0  1  2]
[10 20 30 40]
[0.5 1.  1.5 2. ]


In [28]:
#Slicing
import numpy as np
arr=([1,2,5,6,7])
print(arr[1])
arr[2:5]

2


[5, 6, 7]

In [32]:
#unary operations
arr = np.array([[1,5, 12],
                [2,32, 20],
                [3, 40, 13]])
 
 
print(arr.max(axis = 1))  # using row
print(arr.max(axis = 0))  # column
 
print(arr.min(axis = 0))   #using column
print(arr.min(axis = 1))   # row
 
print ( arr.sum())

[12 32 40]
[ 3 40 20]
[ 1  5 12]
[1 2 3]
128


In [9]:
#binary operations
import numpy as np
 
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
print (a + b)
print (a*b)
print (np.around(a/b,2))

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[0.25 0.67]
 [1.5  4.  ]]


In [ ]:
1. Write a Python program to convert a list and tuple into Numpy arrays.

List to array: [1 2 3 4 5 6 7 8] 
Tuple to array:
[[8 4 6]  [1 2 3]]

Discuss how the list and tuple differ from the arrays.

2. Write a Python program to append values to the end of a Numpy array. 

Expected Output:
Original array:
 [10, 20, 30] 
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
NUMPY Arrays



In [13]:
import numpy as np
mylist = [1,2,3,4,5]

arrayA = np.asarray(mylist)

print(arrayA)

mytuple = ([1,2,13,2], [1,3,5,2])

arrayB = np.asarray(mytuple)
print(arrayB)


arrayC = np.append(arrayA, arrayB)
print(arrayC)

[1 2 3 4 5]
[[ 1  2 13  2]
 [ 1  3  5  2]]
[ 1  2  3  4  5  1  2 13  2  1  3  5  2]


In [17]:
import numpy as np
x = [10,20,30]
print("original list: ", x)

myarry = np.append(x,[[40, 50, 60], [70, 80, 90]])

print(myarry)



original list:  [10, 20, 30]
[10 20 30 40 50 60 70 80 90]


In [26]:
myarry[0:3]

array([10, 20, 30])